Update Saber and add AVX2 implementation
PQClean/PQClean pull request #340
Opened 2020-10-16 00:17 UTC by jschanck

New Saber packaging script at https://github.com/jschanck/package-pqclean pulling from https://github.com/KULeuven-COSIC/SABER.

This PR updates the clean implementations and adds AVX2 implementations.

2020-10-16 16:39 UTC, jschanck commented
Occurs to me that I should have packaged the AVX2 code that uses keccak4x. Shouldn't be difficult, but I'm marking as draft for now.

2020-10-20 15:41 UTC, jschanck commented
Relevant tests passed.

2020-10-23 07:14 UTC, thomwiggers commented
Rebasing on master (pulling in #338) should reduce the number of builds run by quite a bit.

2020-10-23 07:24 UTC, thomwiggers requested changes
Thanks for the contribution.

The SABER code isn't the greatest; and I've found some things where I thought "hmm". Notably I suspect there are a lot of variables that require explicit alignment...

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/SABER_indcpa.c
> +//#include "./polymul/toom_cook_4/toom-cook_4way.c"
These commented lines can probably go away

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/SABER_indcpa.c
> +#include "./polymul/toom-cook_4way.c"
``#include``-ing a `.c` file?

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/kem.c
> +    uint8_t buf[64];
how are the alignment requirements on these buffers... I know the Kyber AVX2 code (on which this code is based) does a bunch of aligning here.

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/poly.h
> +} poly;
should this be an aligned type?

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/polymul/toom-cook_4way.c
> +                    r3_avx=a[small_len_avx+3];
This indentation is weird.

2020-10-23 07:24 UTC, thomwiggers commented on crypto_kem/firesaber/avx2/poly.h
> +} poly;
Probably, I've at least tracked down one place where they get cast to `_m256i`.

2020-11-02 08:31 UTC, thomwiggers approved these changes

2020-11-02 08:31 UTC, merged