Update Rainbow to round 3 parameter sets
PQClean/PQClean pull request #361
Opened 2020-11-19 15:59 UTC by mkannwischer

I have updated the parameter sets. 
The code generator is here: https://github.com/mkannwischer/rainbow-clean
Closes #304. 

Note that that "Ia", "IIIc", and "Vc" have been renamed to "I", "III", "V" and note that "cyclic" and "cyclic-compressed" have been renamed to "circumzenithal" (https://en.wikipedia.org/wiki/Circumzenithal_arc) and "compressed".

2020-11-24 10:12 UTC, thomwiggers requested changes
Looks pretty good, small nit so our tests keep running reasonably quickly.

2020-11-24 10:12 UTC, thomwiggers commented on crypto_sign/rainbowI-circumzenithal/clean/Makefile.Microsoft_nmake
> +CFLAGS=/nologo /I ..\..\..\common /W4 /WX
Please re-add ``/O2``

2020-11-27 13:49 UTC, mkannwischer commented on crypto_sign/rainbowI-circumzenithal/clean/Makefile.Microsoft_nmake
> +CFLAGS=/nologo /I ..\..\..\common /W4 /WX
Thanks. done.

2020-11-27 14:14 UTC, thomwiggers approved these changes

2020-11-27 17:55 UTC, merged