Sw update hqc
PQClean/PQClean pull request #512
Opened 2023-09-18 21:08 UTC by SWilson4

Update HQC to conform with the latest submission: see [https://pqc-hqc.org](https://pqc-hqc.org).

I made a number of small changes to the reference code, mostly to eliminate undefined or implementation-defined behaviour. The only substantial change is the addition of a Barrett reduction routine in the code for constant-weight vector sampling. This was to address #482.

It might be easier to review against the reference code: [my fork of the `package-pqclean` repo](https://github.com/SWilson4/package-pqclean/tree/main/hqc) can help with this.

Fixes #482.

#### Manually checked properties
* [ ] Generated Github workflow (run ``.github/workflows/generate_workflows.py``) (new schemes)
* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

2023-09-20 20:48 UTC, SWilson4 commented
The HQC tests are only failing on PPC, due to `astyle` missing: https://github.com/PQClean/PQClean/actions/runs/6252731989/job/16979928238?pr=512#step:6:4502. I've run the non-formatting tests on this branch locally using the PPC container and all the tests pass (except the preprocessor conditional checks for Kyber and Dilithium).

2023-09-21 08:05 UTC, thomwiggers commented
Yeah, we need to merge #500 after which astyle should not run on ppc anymore.

2023-09-21 08:11 UTC, thomwiggers requested changes
Wait, what's happening with the NIST kat random number generators? You're touching an awful lot of meta files.

It might also be better that, if this is necessary, `nist-kat: nist` is the default when not included in a META file.

Additionally, rebasing would be great

2023-09-22 07:07 UTC, thomwiggers commented
I think this looks plausible. @mkannwischer, could you maybe also have a look at the `vector.c` barret reduction mentioned?

2023-10-16 13:43 UTC, thomwiggers approved these changes

2023-10-16 13:43 UTC, merged